packages:
  - apps/*
  - packages/*
  - ../../platform/kb-labs-core/../kb-labs-devkit
  - ../../platform/kb-labs-core/apps/*
  - ../../platform/kb-labs-core/packages/*
  - ../kb-labs-devkit
  - ../kb-labs-host-agent/apps/*
  - ../kb-labs-host-agent/packages/*
  - ../kb-labs-plugin/../kb-labs-devkit
  - ../kb-labs-plugin/packages/*
  - ../kb-labs-plugin/packages/plugin-adapters/*
