packages:
  - apps/*
  - packages/*
  - ../../platform/kb-labs-core/apps/*
  - ../../platform/kb-labs-core/packages/*
  - ../../platform/kb-labs-shared/apps/*
  - ../../platform/kb-labs-shared/packages/*
  - ../kb-labs-devkit
  - ../kb-labs-host-agent/apps/*
  - ../kb-labs-host-agent/packages/*
  - ../kb-labs-plugin/apps/*
  - ../kb-labs-plugin/packages/*
