import { z } from 'zod';

export const TokenTypeSchema = z.enum(['user', 'cli', 'machine']);

export const AuthContextSchema = z.object({
  type: TokenTypeSchema,
  userId: z.string(),
  namespaceId: z.string(),
  tier: z.enum(['free', 'pro', 'enterprise']),
  permissions: z.array(z.string()),
});

export type TokenType = z.infer<typeof TokenTypeSchema>;
export type AuthContext = z.infer<typeof AuthContextSchema>;

// ── JWT / Auth service contracts ─────────────────────────────────────────────

export const RegisterRequestSchema = z.object({
  /** Human-readable name for this agent (e.g. "MacBook Pro") */
  name: z.string().min(1).max(64),
  namespaceId: z.string().min(1).max(64),
  capabilities: z.array(z.string()).default([]),
  /**
   * X25519 public key for E2E encryption, base64url encoded.
   * Generated by the agent; the server stores it for encrypting call payloads.
   */
  publicKey: z.string().optional(),
});

export const RegisterResponseSchema = z.object({
  clientId: z.string(),
  clientSecret: z.string(),
  hostId: z.string(),
});

export const TokenRequestSchema = z.object({
  clientId: z.string(),
  clientSecret: z.string(),
});

export const TokenResponseSchema = z.object({
  accessToken: z.string(),
  refreshToken: z.string(),
  /** Seconds until accessToken expires */
  expiresIn: z.number(),
  tokenType: z.literal('Bearer'),
});

export const RefreshRequestSchema = z.object({
  refreshToken: z.string(),
});

/** JWT payload (sub = hostId) */
export const JwtPayloadSchema = z.object({
  sub: z.string(),       // hostId
  namespaceId: z.string(),
  tier: z.enum(['free', 'pro', 'enterprise']),
  type: TokenTypeSchema,
  iat: z.number(),
  exp: z.number(),
});

export type RegisterRequest = z.infer<typeof RegisterRequestSchema>;
export type RegisterResponse = z.infer<typeof RegisterResponseSchema>;
export type TokenRequest = z.infer<typeof TokenRequestSchema>;
export type TokenResponse = z.infer<typeof TokenResponseSchema>;
export type RefreshRequest = z.infer<typeof RefreshRequestSchema>;
export type JwtPayload = z.infer<typeof JwtPayloadSchema>;
